name: Package Addon

on:
  push:
    branches: [ main ]
    tags: [ "*" ]

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}

    steps:
      - name: Clone project
        uses: actions/checkout@v1
        with:
          fetch-depth: 10

      - name: Package and release Classic
        uses: BigWigsMods/packager@master
        with:
          args: -g classic
